



List DataStarbucks=[
"Starbucks, Bahçelievler",
"Starbucks, Limonluk",
"Starbucks, Yahşi",
"Starbucks, Cami",
"Starbucks, Körfez",
"Starbucks, Maslak Merkez",
"Starbucks, Balçık",
"Starbucks, Şazi Bey",
"Starbucks, Gazi",
"Starbucks, Yüzüncüyıl",
"Starbucks, Cumhuriyet",
"Starbucks, Güzeltepe",
"Starbucks, Kızılay (Kızılay AVM)",
"Starbucks, Pozcu (Forum Mersin AVM)",
"Starbucks, Orta",
"Starbucks, Çayyolu",
"Starbucks, Batı Ataşehir",
"Starbucks, Adalar",
"Starbucks, Selçuklu (Kent Plaza AVM)",
"Starbucks, Gaziemir (Optimum Outlet A..",
"Starbucks, Eyüp (Vialand AVM)",
"Starbucks, Alsancak",
"Starbucks, 4. Levent (Sabancı Center)",
"Starbucks, Zincirlikuyu (Zorlu Center..",
"Starbucks, Beylikdüzü (Beylikdüzü Mig..",
"Starbucks, Ataşehir (Brandium AVM)",
"Starbucks, Atatürk",
"Starbucks, Bilkent (Bilkent Center AV..",
"Starbucks, Eryaman (Optimum Outlet AV..",
"Starbucks, Atatürk Havalimanı",
"Starbucks, Çukurambar (Next Level AVM..",
"Starbucks, Bakırköy (Carousel AVM)",
"Starbucks, Bayrampaşa (Forum İstanbul..",
"Starbucks, Tepebaşı",
"Starbucks, Bakırköy (Capacity AVM)",
"Starbucks, FSM",
"Starbucks, Tepebaşı (Espark AVM)",
"Starbucks, Işıklar",
"Starbucks, Bebek",
"Starbucks, Atakent (Arena Park AVM)",
"Starbucks, Bornova (Forum Bornova AVM..",
"Starbucks, Çankaya (Kentpark AVM)",
"Starbucks, Koru",
"Starbucks, Çankaya (ODTÜ)",
"Starbucks, Levent (Metrocity AVM)",
"Starbucks, Kadıköy",
"Starbucks, Turan Güneş",
"Starbucks, Esenyurt (Torium AVM)",
"Starbucks, Kızılay",
"Starbucks, Göktürk (Sinasos AVM)",



];